name: CART SERVICE PIPELINE

on:
  push:
    branches:
      - main
    paths:
      - cart-service/**
      - docker/backend/cart-service/Dockerfile
      - docker/docker-compose/default/docker-compose.yml
      - .github/workflows/cart-service-*.yml

jobs:
  compile:
    runs-on: self-hosted
    name: Compile project
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup java environment
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Compile project
        run: |
          cd cart-service
          ./mvnw clean compile -DskipTests

  unit-tests:
    runs-on: self-hosted
    name: Unit test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup java environment
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Unit test
        run: |
          cd cart-service
          ./mvnw clean test

  build:
    runs-on: self-hosted
    name: Build project
    needs: [compile, unit-tests]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup java environment
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Build project
        run: |
          cd cart-service
          ./mvnw clean package -DskipTests

  docker:
    runs-on: self-hosted
    name: Build and push to Docker Hub
    needs: [build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup java environment
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Build project
        run: |
          cd cart-service
          ./mvnw clean package

      - name: Extract project version
        id: extract_version
        run: |
          cd cart-service
          echo "VERSION=$(./mvnw -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET_KEY }}

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: cart-service
          file: docker/backend/cart-service/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/cart-service:${{ steps.extract_version.outputs.VERSION }},${{ secrets.DOCKER_USERNAME }}/cart-service:latest
          build-args: |
            PROFILE=default
            APP_VERSION=${{ steps.extract_version.outputs.VERSION }}

  deployment:
    name: Deploy order service
    runs-on: self-hosted
    needs: [ docker ]
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create deployment folder
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "mkdir -p deployment"

      - name: Copy docker compose file
        run: |
          scp docker/docker-compose/default/docker-compose.yml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:deployment/docker-compose.yml

      - name: Set Environment Variables
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} <<EOF
          cd deployment
          docker-compose -f docker-compose.yml down
          docker-compose -f docker-compose.yml pull -q
          docker-compose -f docker-compose.yml up -d
          EOF
          

