name: PRODUCT SERVICE PIPELINE

on:
  push:
    branches:
      - main
    paths:
      - product-service/**
      - docker/backend/product-service/Dockerfile
      - docker/docker-compose/default/docker-compose.yml
      - .github/workflows/product-service-pipeline.yml

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compile project
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup java environment
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "corretto"

      - name: Compile project
        run: |
          cd product-service
          ./mvnw clean package -DskipTests

  unit-tests:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup java environment
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "corretto"

      - name: Unit test
        run: |
          cd product-service
          ./mvnw clean test

  build:
    runs-on: ubuntu-latest
    name: Build project
    needs: [ compile,unit-tests ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup java environment
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Build project
        run: |
          cd product-service
          ./mvnw clean package -DskipTests

  docker:
    runs-on: ubuntu-latest
    name: Build docker image
    needs: [ build ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup java environment
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Build project
        run: |
          cd product-service
          ./mvnw clean package

      - name: Extract project version
        id: extract_version
        run: |
          cd product-service
          echo "VERSION=$(./mvnw -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET_KEY }}

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: product-service
          file: docker/backend/product-service/Dockerfile
          push: true
          platform: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/product-service:${{ steps.extract_version.outputs.VERSION }},${{ secrets.DOCKER_USERNAME }}/product-service:latest
          build-args: |
            PROFILE=default
            APP_VERSION=${{ steps.extract_version.outputs.VERSION }}

  deployment:
    name: Deploy product service
    runs-on: ubuntu-latest
    needs: [ docker ]
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agenet@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create deployment folder
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "mkdir -p deployment"

      - name: Copy docker compose file
        run: |
          scp docker/docker-compose/default/docker-compose.yml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_ID }}:deployment/docker-compose.yml

      - name: Set environment variables
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} <<EOF
          cd deployment
          docker-compose -f docker-compose.yml down
          docker-compose -f docker-compose.yml pull -q
          docker-compose -f docker-compose.yml up -d
          EOF