name: PRODUCT SERVICE PIPELINE

on:
  push:
    branches:
      - main
    paths:
      - product-service/**
      - docker/backend/product-service/Dockerfile
      - docker/docker-compose/default/docker-compose.yml
      - .github/workflows/product-service-pipeline.yml

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compile project
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup java environment
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "corretto"

      - name: Compile project
        run: |
          cd product-service
          ./mvnw clean package -DskipTests

  unit-tests:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup java environment
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "corretto"

      - name: Unit test
        run: |
          cd product-service
          ./mvnw clean test

  build:
    runs-on: ubuntu-latest
    name: Build project
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup java environment
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Build project
        run: |
          cd product-service
          ./mvnw clean package -DskipTests

  docker:
    runs-on: ubuntu-latest
    name: Build docker image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup java environment
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Build project
        run: |
          cd product-service
          ./mvnw clean package

      - name: Extract project version
        id: extract_version
        run: |
          cd product-service
          echo "VERSION=$(./mvnw -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET_KEY }}

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: project-service
          file: docker/backend/product-service/Dockerfile
          push: true
          platform: linux/amd64
          tags: ${{ secrets.DOCKER_USERNAME }}/product-service:${{ steps.extract_version.outputs.VERSION }},${{ secrets.DOCKERHUB_USERNAME }}/product-service:latest
          build-args: |
            PROFILE=default
            APP_VERSION=${{ steps.extract_version.outputs.VERSION }}